services:
  postgres:
    image: postgres:17.4-alpine
    env_file:
      - .env
    ports:
      - 5252:5432
    volumes:
      - $PWD/.data/postgres:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s